version: "3.8"
services:
  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SERVICE_NAME: account

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SERVICE_NAME: cart

  inventory:
    build:
      context: ./inventory
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SERVICE_NAME: inventory

  order-status:
    build:
      context: ./order-status
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SERVICE_NAME: order-status

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SERVICE_NAME: payment

  place-order:
    build:
      context: ./place-order
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      SERVICE_NAME: place-order

  product-review:
    build:
      context: ./product-review
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      SERVICE_NAME: product-review

  recommendation:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      SERVICE_NAME: recommendation

  recommendation-generation:
    build:
      context: ./recommendation-generation
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SERVICE_NAME: recommendation-generation

  search:
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      SERVICE_NAME: search

  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      SERVICE_NAME: shipping
